export interface Module {
  id: string;
  title: string;
  description: string;
  phase: number;
  order: number;
  duration: string;
  prerequisites: string[];
  learningObjectives: string[];
  mentalModels: string[];
  hasInteractiveDemo: boolean;
  hasDiagram: boolean;
  hasChallenge: boolean;
  hasCodeComparison: boolean;
  roadmapUrl?: string;
}

export interface Phase {
  id: number;
  title: string;
  description: string;
  icon: string;
  modules: Module[];
}

const ROADMAP = "https://roadmap.sh/frontend";

export const curriculum: Phase[] = [
  {
    id: 0,
    title: "Orientation",
    description: "A 10-minute map of what you're about to learn",
    icon: "Map",
    modules: [
      {
        id: "0-1-the-map",
        title: "The Map: How Modern Frontend Apps Are Shaped",
        description: "Three lives of an app: written, built, running",
        phase: 0,
        order: 1,
        duration: "10 mins",
        prerequisites: [],
        learningObjectives: [
          "Name the three lives of a modern frontend app (source, build, runtime)",
          "Map each curriculum phase onto the architecture diagram",
          "Recognize what 'modern' is adding on top of plain HTML+JS",
        ],
        mentalModels: [
          "Source code, bundle, and running app are three different things",
          "Each life has its own debugging surface",
          "The build step is the hinge between writing and running",
        ],
        hasInteractiveDemo: false,
        hasDiagram: true,
        hasChallenge: false,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
    ],
  },
  {
    id: 1,
    title: "Internet & Web Foundations",
    description: "How the web actually works under the hood",
    icon: "Globe",
    modules: [
      {
        id: "1-1-how-the-internet-works",
        title: "How the Internet Works",
        description: "DNS, TCP/IP, HTTP, TLS — the layered postal system that delivers every page",
        phase: 1,
        order: 1,
        duration: "30 mins",
        prerequisites: [],
        learningObjectives: [
          "Trace what happens when you type a URL into the browser",
          "Distinguish DNS, IP, TCP, TLS, and HTTP layers",
          "Explain why DNS caching and HTTPS exist",
        ],
        mentalModels: [
          "The internet as a layered postal system",
          "DNS as the phonebook of the web",
          "TCP guarantees delivery; UDP doesn't",
        ],
        hasInteractiveDemo: true,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "1-2-http-and-https",
        title: "HTTP & HTTPS",
        description: "Request/response anatomy, methods, status codes, and what TLS adds",
        phase: 1,
        order: 2,
        duration: "25 mins",
        prerequisites: ["1-1-how-the-internet-works"],
        learningObjectives: [
          "Read an HTTP request/response by hand",
          "Pick the right method and status code for an operation",
          "Explain what HTTPS protects and what it doesn't",
        ],
        mentalModels: [
          "HTTP is a stateless conversation",
          "Status codes are categories: 1xx info, 2xx ok, 3xx redirect, 4xx you, 5xx me",
          "HTTPS = HTTP wrapped in TLS",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "1-3-domain-dns-hosting",
        title: "Domain Names, DNS & Hosting",
        description: "From buying a domain to pointing it at a server (and a CDN)",
        phase: 1,
        order: 3,
        duration: "25 mins",
        prerequisites: ["1-2-http-and-https"],
        learningObjectives: [
          "Configure A, AAAA, CNAME, MX, TXT records on purpose",
          "Pick between static hosting, VPS, and serverless",
          "Explain what a CDN does and when it matters",
        ],
        mentalModels: [
          "Domain → DNS → IP → Server",
          "CDN = your content, geographically duplicated",
          "Edge caching trades freshness for speed",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "1-4-browsers-and-rendering",
        title: "Browsers & the Rendering Pipeline",
        description: "How HTML/CSS/JS turn into pixels: parse → DOM → CSSOM → render → layout → paint",
        phase: 1,
        order: 4,
        duration: "30 mins",
        prerequisites: ["1-3-domain-dns-hosting"],
        learningObjectives: [
          "Walk through the critical rendering path",
          "Identify which CSS/JS patterns block rendering",
          "Reason about layout shift and paint cost",
        ],
        mentalModels: [
          "Render = parse + style + layout + paint + composite",
          "JS blocks parsing; CSS blocks rendering",
          "Reflow is expensive; repaint is cheap",
        ],
        hasInteractiveDemo: false,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
    ],
  },
  {
    id: 2,
    title: "HTML",
    description: "Semantic structure, forms, accessibility, and SEO",
    icon: "Palette",
    modules: [
      {
        id: "2-1-html-basics-and-semantics",
        title: "HTML Basics & Semantic Markup",
        description: "Why <div> soup hurts; using the right element for the right meaning",
        phase: 2,
        order: 1,
        duration: "30 mins",
        prerequisites: ["1-4-browsers-and-rendering"],
        learningObjectives: [
          "Pick the right semantic element (article, section, nav, aside, main)",
          "Build a document outline a screen reader can follow",
          "Diagnose an over-divved page",
        ],
        mentalModels: [
          "HTML is a meaning tree, not a layout tree",
          "Every page has an outline",
          "Accessibility is a side-effect of good HTML",
        ],
        hasInteractiveDemo: true,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "2-2-forms-and-validation",
        title: "Forms & Validation",
        description: "Inputs, labels, native validation, accessible errors",
        phase: 2,
        order: 2,
        duration: "25 mins",
        prerequisites: ["2-1-html-basics-and-semantics"],
        learningObjectives: [
          "Wire labels to inputs three different ways",
          "Use native HTML validation before reaching for JS",
          "Surface errors in an accessible, low-friction way",
        ],
        mentalModels: [
          "The browser ships a validation engine — use it",
          "Label-input association is non-negotiable",
          "Errors should be perceivable and recoverable",
        ],
        hasInteractiveDemo: true,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "2-3-accessibility",
        title: "Accessibility (a11y)",
        description: "WCAG, ARIA, keyboard navigation, screen readers",
        phase: 2,
        order: 3,
        duration: "30 mins",
        prerequisites: ["2-2-forms-and-validation"],
        learningObjectives: [
          "Audit a page for keyboard reachability",
          "Use ARIA only when HTML can't express it",
          "Hit WCAG AA contrast",
        ],
        mentalModels: [
          "First rule of ARIA: don't use ARIA",
          "Keyboard order should match visual order",
          "Accessibility is a baseline, not a feature",
        ],
        hasInteractiveDemo: true,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "2-4-seo-basics",
        title: "SEO Basics",
        description: "Title, meta description, headings, OG tags, robots, sitemap",
        phase: 2,
        order: 4,
        duration: "20 mins",
        prerequisites: ["2-3-accessibility"],
        learningObjectives: [
          "Write a <head> a search engine and a social card both like",
          "Use semantic headings to structure content",
          "Set up robots.txt and a sitemap",
        ],
        mentalModels: [
          "SEO is mostly accessibility plus metadata",
          "<title> and <meta description> are the click-bait you control",
          "Semantic HTML earns ranking for free",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
    ],
  },
  {
    id: 3,
    title: "CSS",
    description: "Styling, layout, responsive design, modern CSS approaches",
    icon: "Sparkles",
    modules: [
      {
        id: "3-1-css-fundamentals",
        title: "CSS Fundamentals",
        description: "Selectors, specificity, the cascade, the box model",
        phase: 3,
        order: 1,
        duration: "30 mins",
        prerequisites: ["2-4-seo-basics"],
        learningObjectives: [
          "Compute specificity by hand",
          "Predict which rule wins when two collide",
          "Reason about content-box vs border-box",
        ],
        mentalModels: [
          "Cascade = origin + specificity + source order",
          "Every element is a box",
          "Inheritance is a feature, not an accident",
        ],
        hasInteractiveDemo: true,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "3-2-flexbox-and-grid",
        title: "Flexbox & Grid",
        description: "Modern layout: when to reach for flex, when to reach for grid",
        phase: 3,
        order: 2,
        duration: "35 mins",
        prerequisites: ["3-1-css-fundamentals"],
        learningObjectives: [
          "Build a row/column layout with flexbox",
          "Build a 2-D layout with grid",
          "Pick between them deliberately",
        ],
        mentalModels: [
          "Flex is 1-D; grid is 2-D",
          "Flex distributes space; grid divides it",
          "fr is the unit of remaining space",
        ],
        hasInteractiveDemo: true,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "3-3-responsive-design",
        title: "Responsive Design",
        description: "Media queries, fluid type, container queries, mobile-first",
        phase: 3,
        order: 3,
        duration: "25 mins",
        prerequisites: ["3-2-flexbox-and-grid"],
        learningObjectives: [
          "Design mobile-first, then enhance",
          "Use clamp() and container queries",
          "Pick breakpoints from content, not devices",
        ],
        mentalModels: [
          "Mobile-first = additive media queries",
          "Breakpoints follow the content, not the iPhone catalog",
          "Container queries > viewport queries (where supported)",
        ],
        hasInteractiveDemo: true,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "3-4-writing-css-modern",
        title: "Tailwind CSS",
        description: "Utility-first CSS, in depth — alternatives mentioned at the end",
        phase: 3,
        order: 4,
        duration: "30 mins",
        prerequisites: ["3-3-responsive-design"],
        learningObjectives: [
          "Compare Tailwind, CSS Modules, CSS-in-JS, styled-components",
          "Pick a styling system based on team and codebase shape",
          "Recognize when not to add a styling library",
        ],
        mentalModels: [
          "Co-location vs cascading — a real tradeoff",
          "Atomic CSS scales utility; semantic CSS scales meaning",
          "Runtime CSS-in-JS has a cost; zero-runtime variants don't",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "3-5-css-architecture-and-preprocessors",
        title: "CSS Architecture & Preprocessors",
        description: "BEM, Sass, PostCSS — naming and tooling for CSS at scale",
        phase: 3,
        order: 5,
        duration: "25 mins",
        prerequisites: ["3-4-writing-css-modern"],
        learningObjectives: [
          "Apply BEM naming to a real component",
          "Use Sass nesting and mixins without nesting too deep",
          "Understand what PostCSS plugins (autoprefixer, presets) do",
        ],
        mentalModels: [
          "BEM = Block__Element--Modifier",
          "Sass is a CSS preprocessor; PostCSS is a CSS post-processor",
          "Architecture beats clever selectors",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
    ],
  },
  {
    id: 4,
    title: "JavaScript",
    description: "Language, DOM, async, fetch",
    icon: "Zap",
    modules: [
      {
        id: "4-1-javascript-fundamentals",
        title: "JavaScript Fundamentals",
        description: "Types, scope, closures, this, modern syntax",
        phase: 4,
        order: 1,
        duration: "35 mins",
        prerequisites: ["3-5-css-architecture-and-preprocessors"],
        learningObjectives: [
          "Distinguish primitives and references",
          "Predict closure behavior",
          "Explain how `this` is bound",
        ],
        mentalModels: [
          "Primitives copy; objects share",
          "A closure is a function plus its lexical environment",
          "`this` is set by the call, not the declaration",
        ],
        hasInteractiveDemo: true,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "4-2-dom-and-events",
        title: "The DOM & Events",
        description: "Querying, mutating, event delegation, the event loop",
        phase: 4,
        order: 2,
        duration: "30 mins",
        prerequisites: ["4-1-javascript-fundamentals"],
        learningObjectives: [
          "Query the DOM efficiently",
          "Use event delegation for dynamic lists",
          "Sketch the event loop with macrotasks and microtasks",
        ],
        mentalModels: [
          "Events bubble, then capture in reverse",
          "Delegation = listen on a parent, dispatch to child",
          "The event loop is a queue of work, not a thread of execution",
        ],
        hasInteractiveDemo: true,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "4-3-fetch-and-async",
        title: "Fetch API & Async JavaScript",
        description: "XHR → Promises → async/await; fetch, AbortController, error handling",
        phase: 4,
        order: 3,
        duration: "30 mins",
        prerequisites: ["4-2-dom-and-events"],
        learningObjectives: [
          "Convert callback hell into async/await",
          "Handle errors in async chains",
          "Cancel an in-flight fetch with AbortController",
        ],
        mentalModels: [
          "A Promise is a value that's not here yet",
          "async/await is sugar over Promises",
          "Errors travel through .catch / try-catch the same way",
        ],
        hasInteractiveDemo: true,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
    ],
  },
  {
    id: 5,
    title: "Workflow & Frameworks",
    description: "Git, package managers, frameworks, TypeScript",
    icon: "Wrench",
    modules: [
      {
        id: "5-1-git-and-github",
        title: "Git & GitHub",
        description: "Branching, PRs, merge vs rebase, conflict resolution",
        phase: 5,
        order: 1,
        duration: "35 mins",
        prerequisites: ["4-3-fetch-and-async"],
        learningObjectives: [
          "Work in feature branches",
          "Resolve a merge conflict without panic",
          "Read git log like a story",
        ],
        mentalModels: [
          "Git tracks snapshots, not diffs",
          "A branch is a movable pointer to a commit",
          "Merge vs rebase = preserve history vs rewrite it",
        ],
        hasInteractiveDemo: false,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "5-2-package-managers",
        title: "Package Managers (npm, pnpm, yarn)",
        description: "Lockfiles, semver, workspaces, why your node_modules is huge",
        phase: 5,
        order: 2,
        duration: "25 mins",
        prerequisites: ["5-1-git-and-github"],
        learningObjectives: [
          "Read a package.json and lockfile",
          "Pin, range, or float a dependency on purpose",
          "Pick between npm, pnpm, and yarn",
        ],
        mentalModels: [
          "package.json declares; lockfile resolves",
          "Semver: major.minor.patch — break, add, fix",
          "pnpm = content-addressed store + symlinks",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "5-3-pick-a-framework",
        title: "React Fundamentals",
        description: "Components, state, JSX, hooks — alternatives mentioned at the end",
        phase: 5,
        order: 3,
        duration: "35 mins",
        prerequisites: ["5-2-package-managers"],
        learningObjectives: [
          "Compare reactivity models across the major frameworks",
          "Recognize where each framework shines",
          "Make a framework choice you can defend",
        ],
        mentalModels: [
          "VDOM diffing (React) vs fine-grained reactivity (Svelte/Solid)",
          "Frameworks differ on where reactivity lives",
          "Boring is fine; the team beats the framework",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "5-4-typescript",
        title: "TypeScript",
        description: "Why types, structural typing, narrowing, generics",
        phase: 5,
        order: 4,
        duration: "30 mins",
        prerequisites: ["5-3-pick-a-framework"],
        learningObjectives: [
          "Add types to a JS file incrementally",
          "Use unions, generics, and narrowing",
          "Read and fix a tsc error",
        ],
        mentalModels: [
          "TS is a type-checker, not a runtime",
          "Structural typing: shape > name",
          "Narrowing turns a union into a single arm",
        ],
        hasInteractiveDemo: true,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
    ],
  },
  {
    id: 6,
    title: "Build, Test & Secure",
    description: "Linters, bundlers, testing, auth, security",
    icon: "Shield",
    modules: [
      {
        id: "6-1-linters-and-formatters",
        title: "Linters & Formatters (ESLint, Prettier)",
        description: "ESLint catches; Prettier formats; never the same job",
        phase: 6,
        order: 1,
        duration: "20 mins",
        prerequisites: ["5-4-typescript"],
        learningObjectives: [
          "Configure ESLint for a TS project",
          "Wire Prettier in without fighting ESLint",
          "Add lint to pre-commit and CI",
        ],
        mentalModels: [
          "Lint = correctness; format = whitespace",
          "Stop arguing about style — let the tool decide",
          "Pre-commit catches what CI shouldn't have to",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "6-2-module-bundlers",
        title: "Vite & the Dev Loop",
        description: "Modern dev server + bundler in depth — alternatives mentioned at the end",
        phase: 6,
        order: 2,
        duration: "30 mins",
        prerequisites: ["6-1-linters-and-formatters"],
        learningObjectives: [
          "Compare Vite, Webpack, esbuild, Rollup, Parcel",
          "Explain HMR and where it fits in the dev loop",
          "Pick a bundler for a given project",
        ],
        mentalModels: [
          "Dev: serve, transform on demand. Build: bundle for the network.",
          "Vite leans on the browser's ESM; Webpack predates it",
          "HMR = update in place, preserve state",
        ],
        hasInteractiveDemo: false,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "6-3-testing",
        title: "Testing (Vitest, Jest, Playwright, Cypress)",
        description: "The pyramid: unit, integration, E2E — and what each catches",
        phase: 6,
        order: 3,
        duration: "30 mins",
        prerequisites: ["6-2-module-bundlers"],
        learningObjectives: [
          "Pick the right level for a given test",
          "Write a component test that fails for the right reason",
          "Set up a Playwright E2E that isn't flaky",
        ],
        mentalModels: [
          "Test pyramid: many cheap, few expensive",
          "Test behavior, not implementation",
          "Flaky tests are bugs",
        ],
        hasInteractiveDemo: false,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "6-4-authentication",
        title: "Authentication Strategies",
        description: "JWT, OAuth, SSO, Basic Auth, Session Auth — pick on purpose",
        phase: 6,
        order: 4,
        duration: "35 mins",
        prerequisites: ["6-3-testing"],
        learningObjectives: [
          "Pick session cookies vs JWT on purpose",
          "Walk through an OAuth Authorization Code + PKCE flow",
          "Distinguish authentication from authorization",
        ],
        mentalModels: [
          "Cookies are sent automatically; tokens aren't",
          "JWT is signed claims, not encrypted ones",
          "OAuth is delegation, not authentication",
        ],
        hasInteractiveDemo: false,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "6-5-web-security",
        title: "Web Security (CORS, HTTPS, CSP, OWASP)",
        description: "XSS, CSRF, CORS, CSP, supply-chain — the OWASP top hits for the frontend",
        phase: 6,
        order: 5,
        duration: "30 mins",
        prerequisites: ["6-4-authentication"],
        learningObjectives: [
          "Spot an XSS sink and patch it",
          "Defend against CSRF with same-site cookies and tokens",
          "Write a sane Content-Security-Policy",
        ],
        mentalModels: [
          "XSS = attacker's JS in your origin",
          "CSRF = attacker's site triggers your authenticated request",
          "CSP = an allowlist for code execution",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
    ],
  },
  {
    id: 7,
    title: "Beyond the Browser & Production",
    description: "Web Components, SSR, GraphQL, SSG, PWA, Mobile, Desktop, Performance",
    icon: "Boxes",
    modules: [
      {
        id: "7-1-web-components",
        title: "Web Components",
        description: "Custom Elements, Shadow DOM, HTML Templates — the platform's component model",
        phase: 7,
        order: 1,
        duration: "30 mins",
        prerequisites: ["6-5-web-security"],
        learningObjectives: [
          "Define a custom element with lifecycle callbacks",
          "Encapsulate styles with Shadow DOM",
          "Use <template> and <slot> for composition",
        ],
        mentalModels: [
          "Custom elements are framework-agnostic components",
          "Shadow DOM = real style encapsulation",
          "<template> is inert HTML you stamp out later",
        ],
        hasInteractiveDemo: true,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "7-2-ssr",
        title: "Server-Side Rendering (Next.js, Nuxt, SvelteKit)",
        description: "Where a page renders changes everything: client, server, build, edge",
        phase: 7,
        order: 2,
        duration: "35 mins",
        prerequisites: ["7-1-web-components"],
        learningObjectives: [
          "Pick CSR / SSR / SSG / ISR / RSC for a route on purpose",
          "Reason about hydration cost",
          "Explain what RSC actually moves",
        ],
        mentalModels: [
          "Rendering location is a slider, not a switch",
          "Hydration = wiring up server HTML on the client",
          "RSC = render some components on the server, never ship their JS",
        ],
        hasInteractiveDemo: false,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "7-3-graphql",
        title: "GraphQL (Apollo, Relay)",
        description: "One query, exactly the data you need",
        phase: 7,
        order: 3,
        duration: "30 mins",
        prerequisites: ["7-2-ssr"],
        learningObjectives: [
          "Read a GraphQL schema",
          "Write a query with fragments and variables",
          "Compare Apollo and Relay clients",
        ],
        mentalModels: [
          "Schema-first design",
          "Client asks; server fulfills exactly",
          "Caching by id, not by URL",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "7-4-static-site-generators",
        title: "Static Site Generators (Astro, Eleventy, Vuepress, Nuxt, Next)",
        description: "Pre-render at build time, ship plain HTML",
        phase: 7,
        order: 4,
        duration: "25 mins",
        prerequisites: ["7-3-graphql"],
        learningObjectives: [
          "Pick an SSG by content shape and team familiarity",
          "Understand islands architecture",
          "Reason about build time vs request time",
        ],
        mentalModels: [
          "Build once, serve many",
          "Islands = mostly-static + sprinkles of JS",
          "SSG is the default; only opt out when you must",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "7-5-pwas-and-browser-apis",
        title: "PWAs & Browser APIs",
        description: "Service workers, storage, sockets, notifications — turning a tab into an app",
        phase: 7,
        order: 5,
        duration: "35 mins",
        prerequisites: ["7-4-static-site-generators"],
        learningObjectives: [
          "Register a service worker that caches the shell",
          "Pick the right storage (LocalStorage, IndexedDB, Cache API)",
          "Use WebSockets and Server-Sent Events on purpose",
        ],
        mentalModels: [
          "Service worker = a programmable proxy",
          "PWA = web app with offline + install + push",
          "Pick the storage that matches the data shape",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "7-6-mobile-apps",
        title: "Mobile Apps (React Native, Flutter, Ionic)",
        description: "Frontend skills, native targets",
        phase: 7,
        order: 6,
        duration: "25 mins",
        prerequisites: ["7-5-pwas-and-browser-apis"],
        learningObjectives: [
          "Compare React Native, Flutter, and Ionic",
          "Pick a stack based on team and target",
          "Recognize when a PWA is enough",
        ],
        mentalModels: [
          "RN: real native UI, JS bridge",
          "Flutter: own renderer, every pixel",
          "Ionic: Web UI in a WebView",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "7-7-desktop-apps",
        title: "Desktop Apps (Electron, Tauri, Flutter)",
        description: "Chromium-everywhere vs native-shell vs Flutter desktop",
        phase: 7,
        order: 7,
        duration: "25 mins",
        prerequisites: ["7-6-mobile-apps"],
        learningObjectives: [
          "Compare Electron, Tauri, and Flutter Desktop",
          "Reason about bundle size, memory, security model",
          "Pick a desktop stack that fits the team",
        ],
        mentalModels: [
          "Electron: Chromium + Node, fat but predictable",
          "Tauri: system webview + Rust core, lean",
          "Flutter desktop: same renderer as mobile",
        ],
        hasInteractiveDemo: false,
        hasDiagram: false,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "7-8-performance",
        title: "Performance (PRPL, RAIL, Lighthouse, DevTools)",
        description: "Measure & improve: Core Web Vitals, Lighthouse, DevTools, performance best practices",
        phase: 7,
        order: 8,
        duration: "35 mins",
        prerequisites: ["7-7-desktop-apps"],
        learningObjectives: [
          "Measure LCP, INP, CLS",
          "Read a Lighthouse report and act on it",
          "Apply PRPL and RAIL on a real route",
        ],
        mentalModels: [
          "LCP = how fast the main thing appears",
          "INP = how snappy interactions feel",
          "RAIL = budget per kind of interaction",
        ],
        hasInteractiveDemo: false,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
    ],
  },
  {
    id: 8,
    title: "How a Modern Frontend App Works (Capstone)",
    description: "Build, request, architecture — one real app, three lenses",
    icon: "Layers",
    modules: [
      {
        id: "8-1-the-build-pipeline",
        title: "The Build Pipeline",
        description: "From source files to a deployed bundle: Vite, transforms, code-splitting, the module graph",
        phase: 8,
        order: 1,
        duration: "35 mins",
        prerequisites: ["6-2-module-bundlers"],
        learningObjectives: [
          "Trace what happens between writing TS and serving JS chunks to the browser",
          "Distinguish dev-mode (on-demand) from build-mode (exhaustive) module graph traversal",
          "Reason about chunk-splitting, tree-shaking, and asset hashing on a real app",
        ],
        mentalModels: [
          "Source code is what you write; the bundle is what runs",
          "The module graph is the bundler's mental model",
          "Build mode picks decisions the browser can't undo",
        ],
        hasInteractiveDemo: true,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
      {
        id: "8-2-the-request-lifecycle",
        title: "The Request Lifecycle",
        description: "URL → DNS → server → HTML → JS → hydration → interactive — the eight machines a single page passes through",
        phase: 8,
        order: 2,
        duration: "35 mins",
        prerequisites: ["7-2-ssr"],
        learningObjectives: [
          "Walk a request from URL bar to first interaction across DNS, CDN, server, browser parser, JS engine, and React",
          "Diagnose where time goes in a real DevTools waterfall",
          "Reason about hydration cost and identify what hydrates vs what stays server-only",
        ],
        mentalModels: [
          "A page appearing in the browser is a relay race across machines",
          "Hydration is wiring up server HTML on the client; it is not the same as render",
          "Time-to-interactive is not the same as time-to-LCP",
        ],
        hasInteractiveDemo: true,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: false,
        roadmapUrl: ROADMAP,
      },
      {
        id: "8-3-the-architecture-of-a-real-app",
        title: "The Architecture of a Real App",
        description: "A folder-by-folder walk through the reference app: routing, server vs client, data, state, mutations, auth, deploy",
        phase: 8,
        order: 3,
        duration: "40 mins",
        prerequisites: ["8-2-the-request-lifecycle", "6-4-authentication"],
        learningObjectives: [
          "Read a Next.js App Router project and place every file on the architecture map",
          "Decide where new code belongs (server component, client component, server action) on purpose",
          "Distinguish URL state, server state, and client state and pick the right one for a feature",
        ],
        mentalModels: [
          "Folder structure encodes architectural decisions",
          "Server components and client components are a deliberate boundary, not a syntax detail",
          "State has three flavors; matching the flavor to the data shape avoids 90% of state-management pain",
        ],
        hasInteractiveDemo: true,
        hasDiagram: true,
        hasChallenge: true,
        hasCodeComparison: true,
        roadmapUrl: ROADMAP,
      },
    ],
  },
];

export function getAllModules(): Module[] {
  return curriculum.flatMap((phase) => phase.modules);
}

export function getModuleById(id: string): Module | undefined {
  return getAllModules().find((module) => module.id === id);
}

export function getModulesByPhase(phaseId: number): Module[] {
  return curriculum.find((p) => p.id === phaseId)?.modules ?? [];
}

export function getNextModule(currentModuleId: string): Module | undefined {
  const all = getAllModules();
  const i = all.findIndex((m) => m.id === currentModuleId);
  if (i === -1 || i === all.length - 1) return undefined;
  return all[i + 1];
}

export function getPreviousModule(currentModuleId: string): Module | undefined {
  const all = getAllModules();
  const i = all.findIndex((m) => m.id === currentModuleId);
  if (i <= 0) return undefined;
  return all[i - 1];
}

export function isModuleUnlocked(_moduleId: string, _completedModules: string[]): boolean {
  return true;
}

export function getPhaseProgress(phaseId: number, completedModules: string[]): number {
  const modules = getModulesByPhase(phaseId);
  if (modules.length === 0) return 0;
  const done = modules.filter((m) => completedModules.includes(m.id)).length;
  return Math.round((done / modules.length) * 100);
}

export function getTotalProgress(completedModules: string[]): number {
  const total = getAllModules().length;
  if (total === 0) return 0;
  return Math.round((completedModules.length / total) * 100);
}
